WebApp_hardware_data/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^hwdata/', include('hwdata.urls')),
]

hwdata/urls.py
from django.conf.urls import url
from . import views

app_name = 'hwdata'

urlpatterns = [
    # /hwdata/
    url(r'^$', views.index, name='index'),
    # /hwdata/json/
    url(r'^json', views.json, name='json'),
]

hwdata/models.py
from django.db import models


# Create your models here.
class Data(models.Model):
    CPU_usage = models.FloatField()
    SWAP_usage = models.FloatField()

    def __str__(self):
        return 'CPU: ' + self.CPU_usage.__str__() + '%, SWAP: ' + self.SWAP_usage.__str__() + '%'

hwdata/views.py
from django.shortcuts import render
from django.http import JsonResponse, HttpResponse
from .models import Data
from psutil import cpu_percent, swap_memory


# Create your views here.
def index(request):
    return render(request, 'hwdata/index.html')


def json(request):
    if request.is_ajax():
        cpu_current_usage = cpu_percent()
        swap_current_usage = (100 * swap_memory().used) / swap_memory().total
        swap_current_usage = round(swap_current_usage, 2)
        Data(CPU_usage=cpu_current_usage, SWAP_usage=swap_current_usage).save()

        records = 20
        exclude_id = Data.objects.count() - records
        if exclude_id > 0:
            id_list = Data.objects.all()[exclude_id:].values_list("id", flat=True)  # only retrieve ids.
            Data.objects.exclude(pk__in=list(id_list)).delete()
        context = {'cpu usage': cpu_current_usage, 'swap usage': swap_current_usage}
        return JsonResponse(context)

    else:
        my_data = Data.objects.all()
        my_data = list(reversed(my_data))
        count = len(my_data)
        return render(request, 'hwdata/json.html', {'current_data': my_data,
                                                    'count': count})

hwdata/templates/hwdata/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %} HW Data{% endblock %}</title>

    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'hwdata/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'hwdata/css/style.css' %}"/>
    <link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet" type="text/css">

    <script src="{% static 'hwdata/js/jquery.min.js' %}"></script>
    <script src="{% static 'hwdata/js/bootstrap.min.js' %}"></script>

    <!-- Load files to build highcharts -->
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
    <script src="{% static 'hwdata/js/highcharts.js' %}"></script>   <!-- IMPORTANT -->
    <script src="https://code.highcharts.com/highcharts.js"></script>
    <script src="https://code.highcharts.com/highcharts-more.js"></script>
    <script src="https://code.highcharts.com/modules/solid-gauge.js"></script>


</head>
<body>
<!-- Navigation Bar -->
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Logo -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'hwdata:index' %}">HW</a>
        </div>
        <!-- End Logo -->

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="{% url 'hwdata:index' %}">
                        <span class="glyphicon glyphicon glyphicon-scale" aria-hidden="true"></span>&nbsp;HW Data
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'hwdata:json' %}">
                        <span class="glyphicon glyphicon glyphicon-book" aria-hidden="true"></span>&nbsp;Json
                    </a>
                </li>
            </ul>

        </div>
        <!-- End Items -->

    </div>
</nav>

{% block body %}
{% endblock %}
</body>
</html>

hwdata/templates/hwdata/index.html
{% extends 'hwdata/base.html' %}
{% block title %}HW Data{% endblock %}


{% block body %}

    <div class="container-fluid">
        <div class="col-md-6 col-md-offset-3">
            <div id="container-cpu" style="width: 300px; height: 200px;float: left;">ff</div>
            <div id="container-swap" style="width: 300px; height: 200px;float: left;"></div>
        </div>
    </div>

{% endblock body %}

hwdata/templates/hwdata/json.html
{% extends 'hwdata/base.html' %}
{% block title %}Json{% endblock %}

{% block body %}

    <div class="container-fluid">
    {% if current_data %}
        <h2>Hardware data:</h2>
        <h3>Storing the latest {{ count }} records:</h3>
        <table class="table table-condensed table-hover">
            <thead>
            <tr class="active">
                <th>Id</th>
                <th>Cpu usage [%]</th>
                <th>Swap usage [%]</th>
            </tr>
            </thead>

            <tbody>
            {% for data in current_data %}
                <tr>
                    <td>{{ data.id }}</td>
                    <td>{{ data.CPU_usage }}</td>
                    <td>{{ data.SWAP_usage }}</td>
                </tr>
            {% endfor %}

            </tbody>
        </table>

    {% else %}
        <h3> No data! </h3>
    {% endif %}

{% endblock body %}

</div>